spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234

#日志级别
logging:
  level:
    com:
      itheima:
        mapper: debug


# springdoc-openapi（knife4j）项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.itheima.controller

#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Alioss配置
aliyun:
  oss:
    access-key-id: LTAI5t7MqF74rAfGtzw5LJxW
    ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-mytails01
    secret-access-key: qJoHgzHdh7ElwbSANjpgRLkPtylpDf
