spring:
  profiles:
    active: local
  #MySQL数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234
  #redis的连接信息
  data:
    redis:
      host: localhost #连接地址
      port: 6379



#日志级别
logging:
  level:
    com:
      itheima:
        mapper: debug


# springdoc-openapi（knife4j）项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.itheima.controller

#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Alioss配置
aliyun:
  oss:
    access-key-id: ${aliyun.oss.access-key-id}
    ENDPOINT: ${aliyun.oss.ENDPOINT}
    bucket-name: ${aliyun.oss.bucket-name}
    secret-access-key: ${aliyun.oss.secret-access-key}
